# Generated by Django 4.2.6 on 2023-10-07 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_register_delete_course_delete_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
